from typing import Dict, List

# Dictionary of CT metadata for COPD patients
# NA: not applicable, 与风险预测无关的变量
# yes: used for prediction, 强风险因素
# maybe: 弱风险因素，可能用于预测
# no: 不能用于预测的变量, 或者有indexed的变量，raw值就不要使用

# ---------------------------------------------------------
# Hand-authored CT metadata (all columns)
# ---------------------------------------------------------
COPD_CT_METADATA_for_CVD_Risk_Prediction: Dict[str, Dict[str, object]] = {
    # identifiers / cohort
    "source": {
        "clinical_domain": "protocol_admin",
        "vtype": "cat",
        "dtype": "string",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Data source cohort (COPDGene or NLST).",
        "notes": "",
    },
    "case": {
        "clinical_domain": "protocol_admin",
        "vtype": "cat",
        "dtype": "string",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Subject identifier; corresponds to sid in clinical data.",
        "notes": "",
    },
    "phase": {
        "clinical_domain": "protocol_admin",
        "vtype": "cat",
        "dtype": "string",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "CT acquisition phase name (e.g., COPDGene, COPDGene-2, COPDGene-3, COPDGene-3B).",
        "notes": "",
    },
    "series": {
        "clinical_domain": "protocol_admin",
        "vtype": "cat",
        "dtype": "string",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Original CT series identifier.",
        "notes": "",
    },
    "optimal_series": {
        "clinical_domain": "protocol_admin",
        "vtype": "cat",
        "dtype": "string",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Selected optimal CT series for analysis based on protocol.",
        "notes": "",
    },

    # geometry
    "size_x": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "CT image size along x-axis (pixels).",
        "notes": "",
    },
    "size_y": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "CT image size along y-axis (pixels).",
        "notes": "",
    },
    "size_z": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "CT image size along z-axis (slices).",
        "notes": "",
    },
    "spacing_x": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Voxel spacing along x-axis (mm).",
        "notes": "",
    },
    "spacing_y": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Voxel spacing along y-axis (mm).",
        "notes": "",
    },
    "spacing_z": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Voxel spacing along z-axis (mm).",
        "notes": "",
    },
    "roi_center_x": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "X-coordinate of cardiac ROI center (voxel space).",
        "notes": "",
    },
    "roi_center_y": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Y-coordinate of cardiac ROI center (voxel space).",
        "notes": "",
    },
    "roi_center_z": {
        "clinical_domain": "ct_geometry",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Z-coordinate of cardiac ROI center (voxel space).",
        "notes": "",
    },

    # chamber volumes
    # 原始测量数据与身高体重强相关， 使用indexed的值更合理，raw值直接排除
    "la_volume": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Left atrial volume measured from CT (mL).",
        "notes": "",
    },
    "lv_volume": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Left ventricular volume measured from CT (mL).",
        "notes": "",
    },
    "ra_volume": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Right atrial volume measured from CT (mL).",
        "notes": "",
    },
    "rv_volume": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Right ventricular volume measured from CT (mL).",
        "notes": "",
    },

    # indexed volumes
    "la_volume_indexed": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Left atrial volume indexed by body surface area.",
        "notes": "",
    },
    "lv_volume_indexed": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Left ventricular volume indexed by body surface area.",
        "notes": "",
    },
    "ra_volume_indexed": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Right atrial volume indexed by body surface area.",
        "notes": "",
    },
    "rv_volume_indexed": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Right ventricular volume indexed by body surface area.",
        "notes": "",
    },

    # 血管直径 对体型、性别高度敏感
    # vascular
    "ascending_aorta_diameter": {
        "clinical_domain": "ct_vascular",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Diameter of ascending aorta measured from CT (mm).",
        "notes": "",
    },
    "ascending_aorta_index": {
        "clinical_domain": "ct_vascular",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Ascending aorta diameter indexed by body size.",
        "notes": "",
    },

    # 没有indexed的变量， 直接排除。如果使用，可以先将其除以bsa，转为indexed
    "descending_aorta_diameter": {
        "clinical_domain": "ct_vascular",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Diameter of descending aorta measured from CT (mm).",
        "notes": "",
    },

    # PA diameter → 肺高压 proxy（在 COPD 人群中尤其重要）
    "pa_diameter": {
        "clinical_domain": "ct_vascular",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Pulmonary artery diameter measured from CT (mm).",
        "notes": "",
    },
    "pa_index": {
        "clinical_domain": "ct_vascular",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Pulmonary artery diameter indexed by body size.",
        "notes": "",
    },

    # ✅ 保留 & 核心
    #     •	ascending_aorta_index
    #     •	aortic_size_index
    #     •	pa_index
    #     •	pa_to_aa_ratio
    #     •	la_lv_ratio
    #     •	rv_lv_ratio
    #     •	ra_rv_ratio

    # ⚠️ 保留但降权（secondary）
    #     •	ascending_aorta_diameter
    #     •	descending_aorta_diameter
    #     •	pa_diameter
    #     •	aortic_ratio

    # ❌ 建议不用于 prediction
    #     •	ra_la_ratio
    #     •	atria_ventricle_ratio
    #     •	right_left_ratio
    #     •	atria_total_ratio
    #     •	left_total_ratio
    #     •	right_total_ratio


    # 强烈建议保留（这是 ratio 里最有价值的一个）
    # 肺高压的 经典 CT surrogate， 在 COPD / CVD overlap 人群中极其关键
    # 比单独 PA diameter 稳健得多
    "pa_to_aa_ratio": {
        "clinical_domain": "ct_vascular",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Pulmonary artery to ascending aorta diameter ratio.",
        "notes": "",
    },

    # indexed vascular
    "aortic_size_index": {
        "clinical_domain": "ct_vascular",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Composite index of aortic size relative to body size.",
        "notes": "",
    },

    # aortic_ratio 更多是反映局部扩张，而非绝对风险
    # 直接 predictive power 通常有限, 但对 解释模型决策 有帮助
    "aortic_ratio": {
        "clinical_domain": "ct_vascular",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": True,
        "meaning": "Ratio of ascending to descending aorta diameter.",
        "notes": "",
    },

    # 有明确结构/功能含义的 ratio（推荐保留）
    "la_lv_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Ratio of left atrial to left ventricular volume.",
        "notes": "",
    },
    "ra_rv_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Ratio of right atrial to right ventricular volume.",
        "notes": "",
    },
    "rv_lv_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Ratio of right ventricular to left ventricular volume.",
        "notes": "",
    },

    # 信息高度冗余的 ratio（建议慎用或降权）
    "atria_ventricle_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": True,
        "meaning": "Ratio of total atrial volume to ventricular volume.",
        "notes": "",
    },
    "right_left_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": True,
        "meaning": "Ratio of total right heart to left heart volume.",
        "notes": "",
    },
    "atria_total_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": True,
        "meaning": "Fraction of atrial volume in total heart volume.",
        "notes": "",
    },
    "left_total_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": True,
        "meaning": "Fraction of left heart volume in total heart volume.",
        "notes": "",
    },
    "right_total_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": True,
        "meaning": "Fraction of right heart volume in total heart volume.",
        "notes": "",
    },

    # ra_la_ratio（最不稳定的一个）
    # 左右心房 volume 都容易 segmentation 出错, ratio 会 放大误差
    # 很少有临床文献直接使用这个 ratio
    "ra_la_ratio": {
        "clinical_domain": "ct_chambers",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": True,
        "meaning": "Ratio of right atrial to left atrial volume.",
        "notes": "",
    },


    # wall thickness
    "avg_wall_thickness": {
        "clinical_domain": "ct_wall",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Average myocardial wall thickness from CT (mm).",
        "notes": "",
    },
    "max_wall_thickness": {
        "clinical_domain": "ct_wall",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Maximum myocardial wall thickness from CT (mm).",
        "notes": "",
    },

    # fat
    # Strongly body-size dependent; retained for normalization and interpretation rather than direct prediction.
    "heart_volume": {
        "clinical_domain": "ct_fat",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": True,
        "meaning": "Total heart volume segmented from CT (mL).",
        "notes": "",
    },
    # Moderately body-size dependent; use with winsorization and in conjunction with heart_fat_ratio.
    # Epicardial fat：与 CAD,炎症, 代谢风险有关， 有大量文献支持。即便在 non-gated CT 中，fat segmentation 比 wall 稳定得多
    "heart_fat_volume": {
        "clinical_domain": "ct_fat",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": True,
        "meaning": "Epicardial and pericardial fat volume (mL).",
        "notes": "",
    },
    # Scale-invariant and robust CT-derived marker; preferred over raw volumes for risk prediction.
    "heart_fat_ratio": {
        "clinical_domain": "ct_fat",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Ratio of heart fat volume to total heart volume.",
        "notes": "",
    },

    # calcium
    # Primary CAC feature for risk prediction; broadly available across cohort.
    "agatston_score": {
        "clinical_domain": "ct_cac",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": True,
        "meaning": "Computed Agatston coronary calcium score.",
        "notes": "",
    },
    "gt_agatston_score": {
        "clinical_domain": "ct_cac",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Ground-truth Agatston score from reference annotation.",
        "notes": "",
    },

    # demographics
    "gender": {
        "clinical_domain": "demographics",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Sex/gender indicator.",
        "notes": "",
    },
    # age 二选一
    "age_baseline": {
        "clinical_domain": "demographics",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "no",
        "need_filtering": False,
        "meaning": "Age at baseline visit (years).",
        "notes": "",
    },
    "age_visit": {
        "clinical_domain": "demographics",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Age at CT visit (years).",
        "notes": "",
    },
    "race": {
        "clinical_domain": "demographics",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Self-reported race.",
        "notes": "",
    },
    # missing too many values
    "ethnic": {
        "clinical_domain": "demographics",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Self-reported ethnicity.",
        "notes": "",
    },

    # anthropometrics / vitals
    "height": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Height (cm).",
        "notes": "",
    },
    "weight": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Weight (kg).",
        "notes": "",
    },
    # too many missing values
    "waist": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Waist circumference (cm).",
        "notes": "",
    },
    "arm_span": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Arm span (cm).",
        "notes": "",
    },
    "bmi": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Body mass index.",
        "notes": "",
    },
    "bsa": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Body surface area.",
        "notes": "",
    },

    # 血压（非常重要，强烈建议保留）
    "sys_bp": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Systolic blood pressure (mmHg).",
        "notes": "",
    },
    "dias_bp": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Diastolic blood pressure (mmHg).",
        "notes": "",
    },
    "resting_sao2": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Resting oxygen saturation (%).",
        "notes": "",
    },

    # 风险中等, 建议：保留，但不要指望它贡献很大
    "heart_rate": {
        "clinical_domain": "vitals",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Heart rate (bpm).",
        "notes": "",
    },


    # oxygen therapy
    # 严重 COPD / 慢性低氧 / 终末状态 proxy
    # 做COPD分析可以使用，但这三个有冗余
    "o2_therapy": {
        "clinical_domain": "medications",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "On oxygen therapy indicator.",
        "notes": "",
    },
    "o2_therapy_hours": {
        "clinical_domain": "medications",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Hours per day of oxygen therapy.",
        "notes": "",
    },
    "o2_therapy_years": {
        "clinical_domain": "medications",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Years on oxygen therapy.",
        "notes": "",
    },

    # smoking / alcohol
    "smoking_status": {
        "clinical_domain": "smoking",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Current smoking status.",
        "notes": "",
    },
    "smoking_stop_age": {
        "clinical_domain": "smoking",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Age stopped smoking.",
        "notes": "",
    },
    "smoking_start_age": {
        "clinical_domain": "smoking",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Age started smoking.",
        "notes": "",
    },
    "quit_smoking_years": {
        "clinical_domain": "smoking",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Years since quitting smoking.",
        "notes": "",
    },
    "smoking_duration": {
        "clinical_domain": "smoking",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Total duration of smoking (years).",
        "notes": "",
    },
    "alcohol_how_often": {
        "clinical_domain": "other",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Alcohol consumption frequency.",
        "notes": "",
    },

    # procedures / outcomes
    "cabg": {
        "clinical_domain": "outcomes_labels",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "History of CABG surgery.",
        "notes": "",
    },
    "angioplasty": {
        "clinical_domain": "outcomes_labels",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "History of angioplasty.",
        "notes": "",
    },
    "cvd_cause_death": {
        "clinical_domain": "outcomes_labels",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Cardiovascular cause of death indicator.",
        "notes": "",
    },
    "all_cause_death": {
        "clinical_domain": "outcomes_labels",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "All-cause death indicator.",
        "notes": "",
    },
    "years_to_death": {
        "clinical_domain": "outcomes_labels",
        "vtype": "num",
        "dtype": "float64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Years from baseline to death.",
        "notes": "",
    },

    # diagnoses (mostly binary/int codes)
    # 可用, Framingham / ASCVD 风险模型中标准协变量, 明确在 CVD 发生前存在
    # 不等价于 CVD, 但显著改变长期风险
    "diag_diabetes": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Diabetes diagnosis.",
        "notes": "",
    },
    "diag_high_blood_pres": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Hypertension diagnosis.",
        "notes": "",
    },
    "diag_high_cholest": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Hypercholesterolemia diagnosis.",
        "notes": "",
    },
    "diag_sleep_apnea": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Sleep apnea diagnosis.",
        "notes": "",
    },
    "diag_blood_clots": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "yes",
        "need_filtering": False,
        "meaning": "Blood clots history.",
        "notes": "",
    },

    # 非心血管疾病（原则上可以用，但价值有限）
    "diag_cancer_kidney": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Kidney cancer diagnosis.",
        "notes": "",
    },
    "diag_gout": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Gout diagnosis.",
        "notes": "",
    },
    "diag_connective_tissue_dz": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Connective tissue disease diagnosis.",
        "notes": "",
    },
    "diag_rheum_arth": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Rheumatoid arthritis diagnosis.",
        "notes": "",
    },
    "diag_cancer_bladder": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Bladder cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_breast": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Breast cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_cervical": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Cervical cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_colon": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Colon cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_esophageal": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Esophageal cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_leukemia": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Leukemia diagnosis.",
        "notes": "",
    },
    "diag_cancer_lung": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Lung cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_lymphoma": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Lymphoma diagnosis.",
        "notes": "",
    },
    "diag_cancer_melanoma": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Melanoma diagnosis.",
        "notes": "",
    },
    "diag_cancer_ovarian": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Ovarian cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_pancreas": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Pancreatic cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_prostate": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Prostate cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_skin": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Skin cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_stomach": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Stomach cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_throat_mouth": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Throat/mouth cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_thyroid": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Thyroid cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_trans_cell": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Transitional cell cancer diagnosis.",
        "notes": "",
    },
    "diag_cancer_uterine": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Uterine cancer diagnosis.",
        "notes": "",
    },
    "diag_anemia": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Anemia diagnosis.",
        "notes": "",
    },
    "diag_asthma": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Asthma diagnosis.",
        "notes": "",
    },
    "diag_asbestosis": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Asbestosis diagnosis.",
        "notes": "",
    },
    "diag_bronch_attack": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "History of bronchial attack.",
        "notes": "",
    },
    "diag_bronchiectasis": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Bronchiectasis diagnosis.",
        "notes": "",
    },
    "diag_chron_bronch": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Chronic bronchitis diagnosis.",
        "notes": "",
    },
    "diag_cognitive_disorder": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Cognitive disorder diagnosis.",
        "notes": "",
    },
    "diag_compress_frac_back": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Compression fracture of back diagnosis.",
        "notes": "",
    },
    "diag_copd": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "COPD diagnosis.",
        "notes": "",
    },
    "diag_emphysema": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Emphysema diagnosis.",
        "notes": "",
    },
    "diag_fibrosis_lung": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Pulmonary fibrosis diagnosis.",
        "notes": "",
    },
    "diag_gastro_esoph_reflx": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "GERD diagnosis.",
        "notes": "",
    },
    "diag_hay_fev": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Hay fever diagnosis.",
        "notes": "",
    },
    "diag_hip_fracture": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Hip fracture history.",
        "notes": "",
    },
    "diag_kidney_disease": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Kidney disease diagnosis.",
        "notes": "",
    },
    "diag_liver_disease": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Liver disease diagnosis.",
        "notes": "",
    },
    "diag_macular_degen": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Macular degeneration diagnosis.",
        "notes": "",
    },
    "diag_osteo_arth": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Osteoarthritis diagnosis.",
        "notes": "",
    },
    "diag_osteoporosis": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Osteoporosis diagnosis.",
        "notes": "",
    },
    "diag_pneumonia": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Pneumonia diagnosis.",
        "notes": "",
    },
    "diag_pneumothorax": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Pneumothorax diagnosis.",
        "notes": "",
    },
    "diag_sarcoidosis": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Sarcoidosis diagnosis.",
        "notes": "",
    },
    "diag_silicosis": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Silicosis diagnosis.",
        "notes": "",
    },
    "diag_stomach_ulcers": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Stomach ulcer diagnosis.",
        "notes": "",
    },
    "diag_tuberculosis": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "maybe",
        "need_filtering": False,
        "meaning": "Tuberculosis diagnosis.",
        "notes": "",
    },

    # CVD
    "diag_coronary_artery": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Coronary artery disease diagnosis.",
        "notes": "",
    },
    "diag_angina": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Angina diagnosis.",
        "notes": "",
    },
    "diag_heart_attack": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Myocardial infarction history.",
        "notes": "",
    },
    "diag_afib": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Atrial fibrillation diagnosis.",
        "notes": "",
    },
    "diag_heart_fail": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Heart failure diagnosis.",
        "notes": "",
    },
    "diag_stroke": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Stroke history.",
        "notes": "",
    },
    "diag_tia": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Transient ischemic attack history.",
        "notes": "",
    },
    "diag_periph_vascular": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Peripheral vascular disease diagnosis.",
        "notes": "",
    },
    "diag_cvd": {
        "clinical_domain": "comorbidity_history",
        "vtype": "cat",
        "dtype": "Int64",
        "used_for_prediction": "NA",
        "need_filtering": False,
        "meaning": "Composite cardiovascular disease indicator.",
        "notes": "",
    },
}